url: http://erichansander.com
feed_url: http://erichansander.com/feed
# twitter: site_twitter_handle

lang: en

title: Eric Hansander's point
title_tooltip: ... now if only I could find a long enough lever...
subtitle: Things and thoughts <a href="/about">I</a> think you'll like

owner:
    name: Eric Hansander
    email: ehdr@erichansander.com
    google_plus:
        url: EricHansander
        number: 102307140318741294467
    twitter: erichansander
    linkedin: erichansander

open_graph: true
twitter_cards: true

future: false
pygments: true

permalink: /b/:title/

markdown: redcarpet

port: 8888

# For more things to configure (including date format), see _includes/custom/*
