url: http://erichansander.com
title: Eric Hansander's point
title_tooltip: ... now if only I could find a long enough lever...
author: Eric Hansander

future: false
pygments: true

permalink: /b/:title/

markdown: redcarpet

port: 8888

# For more things to configure (including date format), see _includes/custom/*
