url: http://erichansander.com
feed_url: http://erichansander.com/feed
# twitter: site_twitter_handle

lang: en

title: Eric Hansander's point
title_tooltip: ... now if only I could find a long enough lever...
subtitle: Things and thoughts <a href="/about">I</a> think you'll like

owner:
    name: Eric Hansander
    email: ehdr@erichansander.com
    google_plus:
        url: EricHansander
        number: 102307140318741294467
    twitter: erichansander
    linkedin: erichansander

open_graph: true
twitter_cards: true

future: false
pygments: true

permalink: /b/:title/

markdown: kramdown

kramdown:
    auto_ids: true
    footnote_nr: 1
    toc_levels: 1..3
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    use_coderay: false

    coderay:
        coderay_wrap: div
        coderay_line_numbers: inline
        coderay_line_numbers_start: 1
        coderay_tab_width: 4
        coderay_bold_every: 10
        coderay_css: style


port: 8888

# For more things to configure (including date format), see _includes/custom/*
