url: http://erichansander.com
feed_url: http://erichansander.com/feed

title: Eric Hansander's point
title_tooltip: ... now if only I could find a long enough lever...

author_name: Eric Hansander
author_email: ehdr@erichansander.com

future: false
pygments: true

permalink: /b/:title/

markdown: redcarpet

port: 8888

# For more things to configure (including date format), see _includes/custom/*
